/* Apresentação do painel. Usa as APIs, permissões e estados existentes. */
function mountAdminShell(){
 const cards=[...document.querySelectorAll('#admin-extras>section')];if(cards[0])cards[0].id='admin-payments';if(cards[1])cards[1].id='admin-backup';
 const heading=el.querySelector('h1');if(heading)heading.id='admin-shops';
 AppShell.mount({name:'Grupo Havo',role:'Administrador do SaaS',active:'shops',items:[{id:'inicio',label:'Minha barbearia',icon:'home',group:'Principal',href:'/painel#inicio'},{id:'shops',label:'Barbearias e assinaturas',icon:'scissors',group:'Administração'},{id:'payments',label:'Pagamentos confirmados',icon:'wallet',group:'Administração'},{id:'backup',label:'Backup e operação',icon:'lock',group:'Sistema'}],onSelect:id=>{AppShell.active(id);document.getElementById('admin-'+id)?.scrollIntoView({behavior:'smooth'});}});
}
let perfilAtual=null,caixaAccess=null,homeProducts=null,homeProductsTime=0,agendaModo='dia',agendaAgrupar=false,clientSearch='',reportRange={inicio:today(),fim:today()};
const byId=id=>document.getElementById(id),isOwner=()=>sessao?.papel!=='barbeiro';
const statusLabel=s=>({agendado:'Agendado',concluido:'Concluído',cancelado:'Cancelado'}[s]||s);
const dateLabel=d=>String(d||'').slice(0,10).split('-').reverse().join('/');
const datePlus=(day,n)=>{const d=new Date(day+'T12:00:00-03:00');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);};
const hourNow=()=>new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date());
function panelItems(){
 const items=[{id:'inicio',label:'Início',icon:'home',group:'Principal'},{id:'agenda',label:'Agenda',icon:'calendar',group:'Principal'},{id:'clientes',label:'Clientes',icon:'users',group:'Principal'}];
 const p=caixaAccess?.permissoes;
 if(p?.acessar_pdv){items.push({id:'caixa',label:'Caixa e vendas',icon:'wallet',group:'Operação',href:'/produtos?view='+ (p.registrar_venda?'new':'sales')},{id:'produtos',label:'Produtos',icon:'box',group:'Operação',href:'/produtos?view=products'});if(p.ver_estoque||p.alterar_estoque)items.push({id:'estoque',label:'Estoque',icon:'list',group:'Operação',href:'/produtos?view=stock'});}
 items.push({id:'financeiro',label:isOwner()?'Financeiro':'Minha comissão',icon:'chart',group:'Gestão'});
 if(isOwner())items.push({id:'equipe',label:'Equipe',icon:'users',group:'Gestão'},{id:'relatorios',label:'Relatórios',icon:'chart',group:'Gestão'},{id:'bloqueios',label:'Folgas e bloqueios',icon:'lock',group:'Sistema'},{id:'config',label:'Configurações',icon:'settings',group:'Sistema'},{id:'plano',label:'Plano e assinatura',icon:'wallet',group:'Sistema'},{id:'publica',label:'Minha página',icon:'scissors',group:'Sistema',href:'/b/'+encodeURIComponent(sessao.slug)});
 items.push({id:'perfil',label:'Meu perfil',icon:'user',group:'Sistema'});if(sessao.administrador)items.push({id:'gestao',label:'Gestão do SaaS',icon:'settings',group:'Sistema',href:'/gestao'});return items;
}
async function painel(){
 try{
  sessao=await api('/api/sessao');csrf=sessao.csrf;
  const results=await Promise.all([api(isOwner()?'/api/configuracao':'/api/publico/'+encodeURIComponent(sessao.slug)+'/configuracao'),api('/api/agendamentos'),api('/api/produtos/acesso').catch(()=>null),isOwner()?api('/api/assinatura'):api('/api/meu-perfil')]);
  [config,reservas,caixaAccess]=results;if(isOwner())assinaturaInfo=results[3];else perfilAtual=results[3];
 }catch(err){if(err.status===401){location.replace('/entrar');return;}throw err;}
 UI.accent(config.cor_principal);document.title=config.nome+' · Painel';
 el.innerHTML=`${['inicio','agenda','clientes','financeiro','relatorios','equipe','bloqueios','perfil'].map(id=>`<section id="${id}-area" ${id==='inicio'?'':'class="hidden"'}></section>`).join('')}<section id="config-area" class="hidden"><div class="page-heading"><div><span class="eyebrow">SUA BARBEARIA</span><h1 id="nome-loja">${esc(config.nome)}</h1><p class="muted">Identidade, serviços e horários em um só lugar.</p></div></div><div id="primeiros-passos"></div><div class="card" id="public-page-card"><h2>Página de agendamento</h2><p class="muted">Compartilhe este link com seus clientes.</p><p id="link-publico" class="linkbox"></p><div class="row"><a id="abrir-link" class="button secondary" target="_blank" rel="noopener">Ver minha página</a><button id="copiar-link" class="secondary">Copiar link</button></div></div><div id="config-form-area"></div><details id="subscription-section" class="card"><summary>Plano e assinatura</summary><div id="assinatura-area"></div></details></section>`;
 AppShell.mount({name:config.nome,logo:config.logo_url,role:isOwner()?'Dono / gestor':perfilAtual.profissional,items:panelItems(),active:'inicio',onSelect:mostrarAba});
 if(isOwner()){
  renderConfig();setupConfigSections();renderPrimeirosPassos();renderAssinatura();const link=location.origin+'/b/'+sessao.slug;byId('link-publico').textContent=link;byId('abrir-link').href=link;byId('copiar-link').onclick=async()=>{try{await navigator.clipboard.writeText(link);mensagem('Link copiado.');}catch{mensagem('Copie o endereço mostrado na tela.',true);}};
 }
 renderAgenda();iniciarAgendaAutomatica();
 const requested=location.hash.slice(1),allowed=panelItems().filter(x=>!x.href).map(x=>x.id);await mostrarAba(allowed.includes(requested)?requested:'inicio');
}
async function painelBarbeiro(){return painel();}
async function mostrarAba(a){
 const allowed=panelItems().filter(x=>!x.href).map(x=>x.id);if(!allowed.includes(a))a='inicio';abaAtual=a;limparMensagem();
 for(const id of ['inicio','agenda','clientes','financeiro','relatorios','equipe','bloqueios','perfil','config'])byId(id+'-area')?.classList.toggle('hidden',id!==a&&!(id==='config'&&a==='plano'));
 AppShell.active(a);history.replaceState(null,'','#'+a);
 if(a==='inicio')await renderHome();if(a==='agenda'){listaAgenda();agendaAutomatica?.refresh();}if(a==='clientes')renderClientes();
 if(a==='financeiro'||a==='relatorios')await renderFinanceiro(a);if(a==='equipe'){byId('equipe-area').innerHTML=UI.loading('Carregando equipe…');await renderEquipe();enhanceTeam();}
 if(a==='bloqueios'){byId('bloqueios-area').innerHTML=UI.loading('Carregando bloqueios…');await blocksPage();}if(a==='perfil')renderPerfil();
 if(a==='config'||a==='plano'){byId('config-form-area').hidden=a==='plano';byId('primeiros-passos').hidden=a==='plano';byId('public-page-card').hidden=a==='plano';byId('subscription-section').hidden=a!=='plano';if(a==='plano'){byId('subscription-section').open=true;renderAssinatura();}}
 document.querySelector('main')?.focus({preventScroll:true});
}
function bindPanelActions(root){
 root.querySelectorAll('[data-goto]').forEach(b=>b.onclick=()=>mostrarAba(b.dataset.goto).catch(e=>mensagem(e.message,true)));
 root.querySelectorAll('[data-new-booking]').forEach(b=>b.onclick=()=>newInternalBooking());
 root.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>showAppointment(Number(b.dataset.detail)));
 root.querySelectorAll('[data-complete]').forEach(b=>b.onclick=()=>updateAppointment(Number(b.dataset.complete),'concluido'));
}
function dayReservations(day=today()){return reservas.filter(r=>(r.inicio||'').startsWith(day)).sort((a,b)=>a.inicio.localeCompare(b.inicio)||a.id-b.id);}
function compactAppointment(r){return `<button type="button" class="compact-item" data-detail="${r.id}"><span class="time">${esc(r.inicio.slice(11,16))}</span><span class="item-main"><strong>${esc(r.cliente_nome)}</strong><small>${esc(r.servico_nome)} · ${r.duracao_minutos} min · ${money(r.preco)}${isOwner()?' · '+esc(r.barbeiro_nome):''}</small></span><span class="badge ${r.status}">${statusLabel(r.status)}</span></button>`;}
async function renderHome(refreshProducts=true){
 if(refreshProducts&&isOwner()&&(!homeProducts||Date.now()-homeProductsTime>60000)){try{homeProducts=await api('/api/produtos/resumo?inicio='+today()+'&fim='+today());homeProductsTime=Date.now();}catch{homeProducts=null;}}
 const rows=dayReservations(),done=rows.filter(r=>r.status==='concluido'),pendingRows=rows.filter(r=>r.status==='agendado'),serviceRevenue=done.reduce((s,r)=>s+Number(r.preco),0),next=pendingRows.find(r=>r.inicio.slice(11,16)>=hourNow())||pendingRows[0],name=isOwner()?config.nome:perfilAtual.profissional;
 const hour=Number(hourNow().slice(0,2)),greeting=hour<12?'Bom dia':hour<18?'Boa tarde':'Boa noite';
 const metrics=isOwner()?[[homeProducts?'Faturamento hoje':'Serviços concluídos',money(serviceRevenue+(homeProducts?.total_centavos||0)/100),homeProducts?'Serviços concluídos + produtos':'Produtos indisponíveis no momento'],['Atendimentos hoje',rows.filter(r=>r.status!=='cancelado').length,pendingRows.length+' agendados'],['Ticket médio · serviços',money(done.length?serviceRevenue/done.length:0),'Somente concluídos'],['Clientes atendidos',new Set(done.map(r=>String(r.cliente_telefone).replace(/\D/g,''))).size,'Hoje'],['Vendas de produtos',homeProducts?money(homeProducts.total_centavos/100):'Indisponível',homeProducts?homeProducts.vendas+' vendas confirmadas':'Tente abrir Financeiro']]:[['Atendimentos hoje',rows.filter(r=>r.status!=='cancelado').length,'Sua agenda'],['Concluídos',done.length,'Hoje']];
 byId('inicio-area').innerHTML=AppShell.heading('SEU DIA, ORGANIZADO',`${greeting}, ${name}`,`${pendingRows.length?`Você tem ${pendingRows.length} atendimento${pendingRows.length===1?'':'s'} agendado${pendingRows.length===1?'':'s'} hoje.`:'Sua agenda está em dia. Confira os horários ou crie uma reserva.'}`,`<button data-new-booking>${UI.icon('plus')} Novo agendamento</button>`)+
 (isOwner()&&etapasConfiguracao(config,assinaturaInfo).some(x=>!x.pronto)?`<div class="onboarding-strip"><div><strong>Vamos preparar sua barbearia?</strong><p>${etapasConfiguracao(config,assinaturaInfo).filter(x=>x.pronto).length} de 5 etapas concluídas.</p></div><button data-goto="config">Continuar configuração ${UI.icon('arrow')}</button></div>`:'')+
 `<div class="metrics">${metrics.map(x=>AppShell.metric(...x)).join('')}</div><div class="dashboard-grid ${isOwner()?'owner-home':'staff-home'}"><div><section class="card"><div class="section-heading"><h2>${isOwner()?'Agenda da equipe hoje':'Agenda de hoje'}</h2><button class="quick-link" data-goto="agenda">Ver agenda ${UI.icon('arrow')}</button></div><div class="compact-list">${rows.length?rows.map(compactAppointment).join(''):UI.empty('Nenhum atendimento para hoje','Os novos agendamentos aparecerão aqui automaticamente.')}</div></section>${isOwner()?homeFinance(serviceRevenue):''}</div><div><section class="card next-client"><span class="eyebrow">${next&&next.inicio.slice(11,16)<hourNow()?'ATENDIMENTO PENDENTE':'PRÓXIMO CLIENTE'}</span>${next?`<div class="next-client-time">${esc(next.inicio.slice(11,16))}</div><div class="next-client-person">${UI.avatar(next.cliente_nome)}<div><h2>${esc(next.cliente_nome)}</h2><small>${esc(next.servico_nome)} · ${next.duracao_minutos} min</small></div></div><p>${money(next.preco)}${isOwner()?' · '+esc(next.barbeiro_nome):''}</p><button class="wide" data-detail="${next.id}">Ver atendimento ${UI.icon('arrow')}</button>`:UI.empty('Nenhum cliente aguardando','Novas reservas aparecem na sua agenda.')}</section><div class="quick-actions"><button class="secondary" data-new-booking>${UI.icon('plus')} Novo cliente e agendamento</button>${isOwner()?'<button class="secondary" data-goto="bloqueios">'+UI.icon('lock')+' Bloquear horário</button>':''}${caixaAccess?.permissoes.registrar_venda?'<a class="button secondary" href="/produtos?view=new">'+UI.icon('wallet')+' Registrar venda</a>':''}</div>${isOwner()?lowStockCard():''}</div></div>${isOwner()?teamPerformance(rows):''}<p class="muted" id="home-sync" role="status">Agenda atualizada automaticamente.</p>`;
 bindPanelActions(byId('inicio-area'));
}
function homeFinance(revenue){const commission=dayReservations().filter(r=>r.status==='concluido').reduce((s,r)=>s+Number(r.preco)*r.comissao_pct/100,0);return `<section class="card"><div class="section-heading"><h2>Resumo financeiro · hoje</h2><button data-goto="financeiro" class="quick-link">Ver detalhes ${UI.icon('arrow')}</button></div><div class="detail-facts"><div><small>Serviços concluídos</small><strong>${money(revenue)}</strong></div><div><small>Comissões dos serviços</small><strong>${money(commission)}</strong></div></div><p class="report-note">Os serviços entram neste resumo ao serem concluídos. O sistema ainda não registra o recebimento desses pagamentos.</p></section>`;}
function lowStockCard(){return `<section class="card"><div class="section-heading"><h2>Atenção ao estoque</h2><a href="/produtos?view=stock">Ver estoque</a></div>${homeProducts?homeProducts.estoque_baixo.length?homeProducts.estoque_baixo.slice(0,5).map(p=>`<div class="compact-item"><span class="item-main"><strong>${esc(p.nome)}</strong><small>${esc(Object.values(JSON.parse(p.atributos)).join(' · '))||'Sem variação'}</small></span><span class="badge ${p.quantidade?'low':'zero'}">${p.quantidade?p.quantidade+' un. · Baixo':'Sem estoque'}</span></div>`).join(''):UI.empty('Estoque em dia','Nenhum produto abaixo do mínimo.'):UI.empty('Estoque indisponível','Abra Estoque para tentar novamente.')}</section>`;}
function teamPerformance(rows){return `<section class="card"><div class="section-heading"><h2>Equipe · hoje</h2><button class="quick-link" data-goto="equipe">Ver equipe ${UI.icon('arrow')}</button></div><div class="client-grid">${config.barbeiros.map(b=>{const own=rows.filter(r=>r.barbeiro_id===b.id),done=own.filter(r=>r.status==='concluido');return `<div class="compact-item">${UI.avatar(b.nome)}<span class="item-main"><strong>${esc(b.nome)}</strong><small>${own.filter(r=>r.status!=='cancelado').length} atendimentos · ${done.length} concluídos</small></span><strong>${money(done.reduce((s,r)=>s+Number(r.preco),0))}</strong></div>`;}).join('')||UI.empty('Sua equipe começa aqui','Adicione os profissionais nas configurações.')}</div></section>`;}
function iniciarAgendaAutomatica(){agendaAutomatica=AgendaLive.start({active:()=>['inicio','agenda','clientes'].includes(abaAtual)&&!document.querySelector('dialog[open]')&&!document.querySelector('#lista-reservas button:disabled'),fetchRows:signal=>api('/api/agendamentos',{signal,cache:'no-store'}),current:()=>reservas,render:rows=>{reservas=rows;if(abaAtual==='agenda')listaAgenda();else if(abaAtual==='inicio')renderHome(false);else if(abaAtual==='clientes')renderClientes();},status:text=>{const target=byId(abaAtual==='inicio'?'home-sync':'agenda-sync');if(target)target.textContent=text;},expired:()=>location.replace('/entrar')});}
function renderAgenda(){byId('agenda-area').innerHTML=AppShell.heading('ATENDIMENTOS',isOwner()?'Agenda da barbearia':'Minha agenda','Horários de Brasília. Novas reservas aparecem automaticamente.',`<button data-new-booking>${UI.icon('plus')} Novo agendamento</button>`)+`<div class="toolbar"><div class="segmented"><button id="agenda-day" class="active">Dia</button><button id="agenda-week">Semana</button></div><button class="secondary" id="agenda-hoje">Hoje</button><label>Data<input type="date" id="filtro-data" value="${today()}"></label>${isOwner()?`<label>Profissional<select id="filtro-profissional"><option value="">Toda a equipe</option>${config.barbeiros.map(b=>`<option value="${esc(b.id)}">${esc(b.nome)}</option>`).join('')}</select></label>`:''}<label>Situação<select id="filtro-status"><option value="">Todas</option><option value="agendado">Agendados</option><option value="concluido">Concluídos</option><option value="cancelado">Cancelados</option></select></label></div><div class="row between"><p class="muted" id="agenda-resumo" role="status"></p><div class="row">${isOwner()?'<button class="secondary" id="agenda-group">Separar por profissional</button>':''}<details class="agenda-options"><summary>Mais opções</summary><div class="row"><button id="atualizar" class="secondary">Atualizar</button><button id="todas-datas" class="secondary">Todas as datas</button><button id="exportar" class="secondary">Baixar reservas</button></div></details></div></div><p id="agenda-sync" class="muted" role="status">Atualização automática a cada 10 segundos.</p><div id="lista-reservas" class="agenda-timeline"></div><button class="floating-add" data-new-booking aria-label="Novo agendamento">${UI.icon('plus')}</button>`;
 for(const id of ['filtro-data','filtro-status','filtro-profissional'])if(byId(id))byId(id).onchange=listaAgenda;
 byId('agenda-day').onclick=()=>{agendaModo='dia';listaAgenda();};byId('agenda-week').onclick=()=>{agendaModo='semana';if(!byId('filtro-data').value)byId('filtro-data').value=today();listaAgenda();};byId('agenda-hoje').onclick=()=>{byId('filtro-data').value=today();listaAgenda();};byId('todas-datas').onclick=()=>{byId('filtro-data').value='';listaAgenda();};byId('exportar').onclick=exportar;
 if(byId('agenda-group'))byId('agenda-group').onclick=()=>{agendaAgrupar=!agendaAgrupar;listaAgenda();};byId('atualizar').onclick=async e=>{e.target.disabled=true;try{reservas=await api('/api/agendamentos');listaAgenda();mensagem('Agenda atualizada.');}catch(err){mensagem(err.message,true);}finally{e.target.disabled=false;}};bindPanelActions(byId('agenda-area'));listaAgenda();}
function appointmentCard(r){return `<article class="appointment ${r.status}" data-appointment="${r.id}"><div class="appointment-time">${esc(r.inicio.slice(11,16))}<small>${dateLabel(r.inicio)}</small></div><div><div class="row between"><button class="primary-detail" data-detail="${r.id}">${esc(r.cliente_nome)}</button><span class="badge ${r.status}">${statusLabel(r.status)}</span></div><p>${esc(r.servico_nome)} · ${r.duracao_minutos} min</p><p class="muted">${isOwner()?esc(r.barbeiro_nome)+' · ':''}${money(r.preco)}</p><div class="row appointment-actions">${r.status==='agendado'?`<button class="secondary" data-complete="${r.id}">${UI.icon('check')} Concluir</button>`:''}<button class="secondary" data-detail="${r.id}">Ver detalhes ${UI.icon('arrow')}</button></div></div></article>`;}
function listaAgenda(){const list=byId('lista-reservas');if(!list)return;const day=byId('filtro-data').value,status=byId('filtro-status').value,barber=byId('filtro-profissional')?.value||'',end=day?datePlus(day,agendaModo==='semana'?6:0):'';const rows=reservas.filter(r=>(!day||(r.inicio.slice(0,10)>=day&&r.inicio.slice(0,10)<=end))&&(!status||r.status===status)&&(!barber||r.barbeiro_id===barber));byId('agenda-day').classList.toggle('active',agendaModo==='dia');byId('agenda-week').classList.toggle('active',agendaModo==='semana');byId('agenda-resumo').textContent=`${rows.length} atendimento${rows.length===1?'':'s'}${day?' · '+dateLabel(day)+(end!==day?' a '+dateLabel(end):''):''}`;
 if(byId('agenda-group')){byId('agenda-group').classList.toggle('active',agendaAgrupar);byId('agenda-group').setAttribute('aria-pressed',String(agendaAgrupar));}
 if(!rows.length)list.innerHTML=AppShell.empty('Agenda livre para esta seleção','Escolha outro dia ou crie um novo agendamento.','<button data-new-booking>'+UI.icon('plus')+' Novo agendamento</button>');
 else if(agendaAgrupar&&isOwner()){const ids=[...new Set(rows.map(r=>r.barbeiro_id))];list.innerHTML=`<div class="agenda-columns">${ids.map(id=>`<section class="agenda-column"><div class="agenda-column-title">${UI.avatar(rows.find(r=>r.barbeiro_id===id).barbeiro_nome)}<strong>${esc(rows.find(r=>r.barbeiro_id===id).barbeiro_nome)}</strong></div>${rows.filter(r=>r.barbeiro_id===id).map(appointmentCard).join('')}</section>`).join('')}</div>`;}
 else{let last='';list.innerHTML=rows.map(r=>{const date=r.inicio.slice(0,10),head=agendaModo==='semana'&&date!==last?`<h3 class="agenda-day-heading">${dateLabel(date)}</h3>`:'';last=date;return head+appointmentCard(r);}).join('');}bindPanelActions(list);}
let appointmentUpdating=false;
async function updateAppointment(id,status){if(appointmentUpdating)return;const r=reservas.find(x=>x.id===id);if(!r)return;const words={concluido:['Concluir atendimento?',`Confirme que o atendimento de ${r.cliente_nome} foi realizado. O valor entra no resumo de serviços concluídos; isso não registra um pagamento.`,'Concluir atendimento'],cancelado:['Cancelar agendamento?',`O atendimento de ${r.cliente_nome} será cancelado e o horário será liberado.`,'Cancelar agendamento'],agendado:['Reabrir atendimento?',`O sistema verificará se o horário de ${r.cliente_nome} continua disponível.`,'Reabrir atendimento']};const [title,text,action]=words[status];if(!await AppShell.confirm(title,text,action,status==='cancelado'))return;appointmentUpdating=true;try{await api('/api/agendamentos/'+id,{method:'PATCH',body:JSON.stringify({status})});reservas=await api('/api/agendamentos');if(abaAtual==='agenda')listaAgenda();else if(abaAtual==='clientes')renderClientes();else if(abaAtual==='inicio')await renderHome(false);mensagem(status==='concluido'?'Atendimento concluído.':status==='cancelado'?'Agendamento cancelado.':'Atendimento reaberto.');}catch(e){mensagem(e.message,true);}finally{appointmentUpdating=false;}}
function showAppointment(id){const r=reservas.find(x=>x.id===id);if(!r)return;const d=AppShell.open('Detalhes do atendimento',`<div class="profile-header">${UI.avatar(r.cliente_nome)}<div><h3>${esc(r.cliente_nome)}</h3><span class="badge ${r.status}">${statusLabel(r.status)}</span></div></div><div class="detail-facts"><div><small>Serviço</small><strong>${esc(r.servico_nome)}</strong></div><div><small>Valor</small><strong>${money(r.preco)}</strong></div><div><small>Data e horário</small><strong>${dateLabel(r.inicio)} · ${esc(r.inicio.slice(11,16))}</strong></div><div><small>Profissional · duração</small><strong>${esc(r.barbeiro_nome)} · ${r.duracao_minutos} min</strong></div></div><div class="row"><a class="button secondary" href="${wa(r.cliente_telefone)}" target="_blank" rel="noopener">${UI.icon('phone')} WhatsApp</a><button id="detail-client" class="secondary">Histórico do cliente</button></div><div id="detail-private-link"></div><div class="modal-actions">${isOwner()?`<button class="secondary" id="detail-manage">Link para reagendar</button><button class="${r.status==='agendado'?'danger':'secondary'}" id="detail-change">${r.status==='agendado'?'Cancelar':'Reabrir'}</button>`:''}${r.status==='agendado'?'<button id="detail-finish">'+UI.icon('check')+' Concluir atendimento</button>':''}</div>`);
 byId('detail-client').onclick=()=>showClient(clientKey(r));if(byId('detail-finish'))byId('detail-finish').onclick=()=>updateAppointment(id,'concluido');if(byId('detail-change'))byId('detail-change').onclick=()=>updateAppointment(id,r.status==='agendado'?'cancelado':'agendado');if(byId('detail-manage'))byId('detail-manage').onclick=async e=>{e.target.disabled=true;try{const data=await api('/api/agendamentos/'+id+'/link-cliente',{method:'POST'});byId('detail-private-link').innerHTML=`<p class="muted">Envie somente ao cliente. Este link substitui o anterior.</p><input aria-label="Link privado da reserva" readonly value="${esc(location.origin+data.link)}"><a class="button secondary" target="_blank" rel="noopener" href="${esc(data.link)}">Abrir reagendamento</a>`;}catch(err){mensagem(err.message,true);e.target.disabled=false;}};
}
const clientKey=r=>{let phone=String(r.cliente_telefone).replace(/\D/g,'');if([12,13].includes(phone.length)&&phone.startsWith('55'))phone=phone.slice(2);return phone;};
function clientGroups(){const map=new Map();for(const r of reservas){const key=clientKey(r);if(!map.has(key))map.set(key,[]);map.get(key).push(r);}return [...map].map(([key,rows])=>{rows.sort((a,b)=>a.inicio.localeCompare(b.inicio));const completed=rows.filter(r=>r.status==='concluido');return {key,rows,nome:rows.at(-1).cliente_nome,telefone:rows.at(-1).cliente_telefone,completed,last:completed.at(-1),total:completed.reduce((s,r)=>s+Number(r.preco),0)};}).sort((a,b)=>a.nome.localeCompare(b.nome,'pt-BR'));}
function renderClientes(){const area=byId('clientes-area'),hadFocus=document.activeElement?.id==='client-search',position=document.activeElement?.selectionStart;area.innerHTML=AppShell.heading('RELACIONAMENTO','Clientes',isOwner()?'O histórico dos clientes da sua barbearia.':'Clientes dos seus próprios atendimentos.',`<button data-new-booking>${UI.icon('plus')} Novo cliente e agendamento</button>`)+`<div class="toolbar"><label class="search-field">Buscar cliente<input id="client-search" type="search" placeholder="Nome ou WhatsApp" value="${esc(clientSearch)}"></label></div><div id="client-list" class="client-grid"></div><p class="report-note">Os clientes aparecem a partir dos agendamentos. O total considera serviços concluídos.</p>`;function draw(){const rows=clientGroups().filter(c=>(c.nome+' '+c.telefone).toLowerCase().includes(clientSearch.toLowerCase()));byId('client-list').innerHTML=rows.length?rows.map(c=>`<button class="client-card card" data-client="${esc(c.key)}">${UI.avatar(c.nome)}<span><strong>${esc(c.nome)}</strong><small>${esc(c.telefone)}</small><small>${c.completed.length} atendimentos concluídos · ${c.last?'Última visita '+dateLabel(c.last.inicio):'Ainda sem visita concluída'}</small></span>${UI.icon('arrow')}</button>`).join(''):AppShell.empty('Nenhum cliente encontrado','Os contatos aparecem aqui quando um agendamento é criado.','<button data-new-booking>Adicionar cliente e agendamento</button>');area.querySelectorAll('[data-client]').forEach(b=>b.onclick=()=>showClient(b.dataset.client));bindPanelActions(area);}byId('client-search').oninput=e=>{clientSearch=e.target.value;draw();};draw();if(hadFocus){byId('client-search').focus({preventScroll:true});byId('client-search').setSelectionRange(position,position);}}
function showClient(key){const c=clientGroups().find(x=>x.key===key);if(!c)return;const next=c.rows.find(r=>r.status==='agendado'&&r.inicio>=today()+'T'+hourNow());const d=AppShell.open('Histórico do cliente',`<div class="profile-header">${UI.avatar(c.nome)}<div><h2>${esc(c.nome)}</h2><small>${esc(c.telefone)}</small></div></div><div class="detail-facts"><div><small>Atendimentos concluídos</small><strong>${c.completed.length}</strong></div><div><small>Total em serviços concluídos</small><strong>${money(c.total)}</strong></div><div><small>Última visita</small><strong>${c.last?dateLabel(c.last.inicio):'Sem visita concluída'}</strong></div><div><small>Próxima reserva</small><strong>${next?dateLabel(next.inicio)+' · '+next.inicio.slice(11,16):'Sem agendamento futuro'}</strong></div></div><div class="row"><a class="button secondary" target="_blank" rel="noopener" href="${wa(c.telefone)}">${UI.icon('phone')} WhatsApp</a><button id="book-client">Novo agendamento</button></div><h3 style="margin-top:24px">Atendimentos</h3><div class="compact-list">${[...c.rows].reverse().map(r=>`<div class="compact-item"><span class="item-main"><strong>${esc(r.servico_nome)}</strong><small>${dateLabel(r.inicio)} · ${r.inicio.slice(11,16)} · ${esc(r.barbeiro_nome)} · ${money(r.preco)}</small></span><span class="badge ${r.status}">${statusLabel(r.status)}</span></div>`).join('')}</div>`);byId('book-client').onclick=()=>newInternalBooking({nome:c.nome,telefone:c.telefone});}
function periodControls(){return `<div class="toolbar"><label>Período<select id="report-period"><option value="today">Hoje</option><option value="7">7 dias</option><option value="30">30 dias</option><option value="month">Este mês</option><option value="custom">Personalizado</option></select></label><label>De<input type="date" id="report-start" value="${reportRange.inicio}" required></label><label>Até<input type="date" id="report-end" value="${reportRange.fim}" required></label><button id="report-apply" class="secondary">Aplicar período</button></div>`;}
async function renderFinanceiro(view){const area=byId(view+'-area');area.innerHTML=UI.loading('Organizando os valores…');const rows=reservas.filter(r=>r.inicio.slice(0,10)>=reportRange.inicio&&r.inicio.slice(0,10)<=reportRange.fim),done=rows.filter(r=>r.status==='concluido'),revenue=done.reduce((s,r)=>s+Number(r.preco),0),commission=done.reduce((s,r)=>s+Number(r.preco)*r.comissao_pct/100,0);let products=null;if(caixaAccess?.permissoes.acessar_pdv)try{products=await api('/api/produtos/resumo?'+new URLSearchParams(reportRange));}catch{}
 const cards=isOwner()?[['Serviços concluídos',money(revenue),'Atendimentos realizados'],['Vendas de produtos',products?money(products.total_centavos/100):'Indisponível','Vendas confirmadas'],['Comissões · serviços',money(commission),'Percentual de cada reserva'],['Lucro bruto · produtos',products?.lucro_bruto_centavos!==undefined?money(products.lucro_bruto_centavos/100):'Indisponível','Receita menos custo dos itens']]:[['Atendimentos concluídos',done.length,'No período'],['Minha comissão',money(commission),'Somente serviços concluídos']];
 const categories=[['Serviços','servico_nome'],['Equipe','barbeiro_nome']];area.innerHTML=AppShell.heading('GESTÃO',view==='relatorios'?'Relatórios':isOwner()?'Financeiro':'Minha comissão',isOwner()?'Entenda os valores por origem e por período.':'Acompanhe a comissão dos seus atendimentos realizados.')+periodControls()+`<div class="metrics">${cards.map(x=>AppShell.metric(...x)).join('')}</div>${isOwner()?`<div class="dashboard-grid"><section class="card"><h2>De onde veio o faturamento?</h2><div class="detail-facts"><div><small>Serviços</small><strong>${money(revenue)}</strong></div><div><small>Produtos</small><strong>${products?money(products.total_centavos/100):'Indisponível'}</strong></div></div><p class="price">${products?money(revenue+products.total_centavos/100):money(revenue)}</p><p class="report-note">Serviços representam atendimentos concluídos. Produtos representam vendas confirmadas. Não há controle de recebimento de serviços ou despesas avulsas nesta versão.</p></section><section class="card"><h2>Custos e resultado</h2><p>Custo dos produtos vendidos: <strong>${products?money(products.custo_centavos/100):'Indisponível'}</strong></p><p>Serviços após comissões: <strong>${money(revenue-commission)}</strong></p><p class="report-note">Os valores não representam lucro líquido: aluguel, impostos, taxas e outras despesas não são descontados.</p>${caixaAccess?.permissoes.acessar_pdv?'<a class="button secondary" href="/produtos?view=sales">Ver vendas e pagamentos de produtos</a>':''}</section></div>`:''}${view==='relatorios'?`<div class="metrics">${AppShell.metric('Atendimentos no período',rows.filter(r=>r.status!=='cancelado').length)}${AppShell.metric('Clientes atendidos',new Set(done.map(clientKey)).size)}${AppShell.metric('Ticket médio · serviços',money(done.length?revenue/done.length:0))}</div>${categories.map(([title,key])=>`<section class="card"><h2>${title} · receita concluída</h2>${reportBars(done,key)}</section>`).join('')}<section class="card"><h2>Produtos</h2><p>${products?products.itens_vendidos+' unidades vendidas · '+products.vendas+' vendas confirmadas':'Não foi possível consultar o período.'}</p><a class="button secondary" href="/produtos?view=sales">Consultar vendas por produto</a></section>`:''}<button id="report-export" class="secondary">${UI.icon('list')} Baixar histórico de reservas</button>`;
 byId('report-period').value=reportRange.inicio===today()&&reportRange.fim===today()?'today':'custom';byId('report-period').onchange=e=>{const n=e.target.value;if(n==='custom')return;byId('report-end').value=today();byId('report-start').value=n==='month'?today().slice(0,7)+'-01':datePlus(today(),n==='today'?0:1-Number(n));};byId('report-apply').onclick=async()=>{const start=byId('report-start').value,end=byId('report-end').value;if(!start||!end||start>end||Date.parse(end)-Date.parse(start)>366*86400000){mensagem('Escolha um período válido de até 366 dias.',true);return;}reportRange={inicio:start,fim:end};await renderFinanceiro(view);};byId('report-export').onclick=exportar;
}
function reportBars(rows,key){const map=new Map();rows.forEach(r=>map.set(r[key],(map.get(r[key])||0)+Number(r.preco)));const pairs=[...map].sort((a,b)=>b[1]-a[1]),max=Math.max(1,...pairs.map(x=>x[1]));return pairs.length?`<div class="report-bars">${pairs.map(([name,value])=>`<div class="report-row"><span>${esc(name)}</span><span class="report-track" aria-hidden="true"><span style="width:${value/max*100}%"></span></span><strong>${money(value)}</strong></div>`).join('')}</div>`:UI.empty('Sem atendimentos concluídos','Selecione outro período para consultar.');}
function enhanceTeam(){const area=byId('equipe-area');area.querySelector('h2').textContent='Equipe';const sections=[...area.querySelectorAll('section.card')];sections.forEach((section,i)=>{const b=config.barbeiros[i];if(!b)return;const rows=dayReservations().filter(r=>r.barbeiro_id===b.id),done=rows.filter(r=>r.status==='concluido');section.querySelector('h3')?.remove();section.insertAdjacentHTML('afterbegin',`<div class="profile-header">${UI.avatar(b.nome)}<div><small>PROFISSIONAL</small><h2>${esc(b.nome)}</h2></div></div><p class="muted">Hoje: ${rows.filter(r=>r.status!=='cancelado').length} atendimentos · ${money(done.reduce((s,r)=>s+Number(r.preco),0))} em concluídos</p><button class="secondary" data-team-agenda="${esc(b.id)}">Ver agenda</button>`);section.querySelector('[data-team-agenda]').onclick=()=>{byId('filtro-profissional').value=b.id;byId('filtro-data').value=today();mostrarAba('agenda');};});}
function setupConfigSections(){const area=byId('config-form-area');area.querySelector('.shop-details').open=true;const sections=[['config-loja','Dados e identidade'],['config-localizacao','Localização'],['config-horarios','Horários'],['config-servicos','Serviços'],['config-profissionais','Profissionais']];area.insertAdjacentHTML('afterbegin',`<nav class="config-tabs" aria-label="Configurações">${sections.map(([id,name])=>`<button type="button" class="secondary" data-config-section="${id}">${name}</button>`).join('')}</nav>`);function activate(id){sections.forEach(([key])=>byId(key).hidden=key!==id);area.querySelectorAll('[data-config-section]').forEach(b=>{if(b.dataset.configSection===id)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');});}area.querySelectorAll('[data-config-section]').forEach(b=>b.onclick=()=>activate(b.dataset.configSection));area.addEventListener('invalid',e=>{const card=e.target.closest('#config-form>.card');if(card)activate(card.id);},true);area.activateSection=activate;activate('config-loja');const button=byId('salvar-config'),wrapper=document.createElement('div');wrapper.className='config-save';button.before(wrapper);wrapper.append(button);const original=byId('config-form').onsubmit;byId('config-form').noValidate=true;byId('config-form').onsubmit=async e=>{e.preventDefault();const invalid=e.target.querySelector(':invalid');if(invalid){const card=invalid.closest('#config-form>.card');if(card)activate(card.id);const details=invalid.closest('details');if(details)details.open=true;invalid.reportValidity();invalid.focus();return;}await original(e);UI.accent(config.cor_principal);document.querySelectorAll('.shell-shop-name,.shell-brand strong').forEach(x=>x.textContent=config.nome);const avatar=document.querySelector('.shell-brand .ui-avatar');if(avatar)avatar.outerHTML=UI.avatar(config.nome,config.logo_url);renderAgenda();};}
function renderPerfil(){byId('perfil-area').innerHTML=AppShell.heading('SUA CONTA','Meu perfil','Acesso, horários e ajuda.')+`<section class="card"><div class="profile-header">${UI.avatar(isOwner()?config.nome:perfilAtual.profissional)}<div><h2>${esc(isOwner()?config.nome:perfilAtual.profissional)}</h2><p class="muted">${isOwner()?'Dono / gestor':'Profissional'} · ${esc(sessao.email)}</p></div></div><div class="detail-facts"><div><small>Barbearia</small><strong>${esc(config.nome)}</strong></div><div><small>E-mail</small><strong>${sessao.email_confirmado?'Confirmado':'Aguardando confirmação'}</strong></div></div><h3>Horários da barbearia</h3>${shopHours()}${!isOwner()?'<p class="report-note">Peça ao dono para ajustar seus horários ou bloquear um período.</p>':''}<div class="quick-actions"><a class="button secondary" href="/recuperar-senha">Alterar senha</a><a class="button secondary" href="/suporte">Ajuda e suporte</a><button class="danger" id="profile-logout">${UI.icon('logout')} Sair da conta</button></div></section>`;emailNotice();byId('profile-logout').onclick=async e=>{e.target.disabled=true;try{await api('/api/logout',{method:'POST'});AgendaLive.stop();location.href='/entrar';}catch(err){mensagem(err.message,true);e.target.disabled=false;}};}
function newInternalBooking(prefill={}){
 const draft={nome:prefill.nome||'',telefone:prefill.telefone||'',servico:config.servicos[0]?.id||'',barbeiro:isOwner()?config.barbeiros[0]?.id||'':sessao.barbeiro_id,data:prefill.data||today(),horario:''};let step=0,available=[],version=0,busy=false;
 function render(){
  const service=config.servicos.find(x=>x.id===draft.servico),barber=config.barbeiros.find(x=>x.id===draft.barbeiro),titles=['Quem é o cliente?','Escolha o serviço','Escolha o profissional','Escolha a data','Escolha o horário','Revise o agendamento'];
  const content=step===0?`<label>Nome do cliente<input id="new-client-name" autocomplete="name" value="${esc(draft.nome)}" minlength="2" maxlength="100" required></label><label>WhatsApp com DDD<input id="new-client-phone" type="tel" autocomplete="tel" value="${esc(draft.telefone)}" placeholder="(61) 99999-9999" maxlength="25" required></label>`:step===1?`<div class="choice-grid">${config.servicos.map(s=>UI.choice({id:s.id,title:s.nome,detail:s.duracao+' minutos',price:money(s.preco),selected:s.id===draft.servico})).join('')||UI.empty('Sem serviços cadastrados','O dono precisa configurar os serviços antes de agendar.')}</div>`:step===2?`<div class="choice-grid">${config.barbeiros.filter(b=>isOwner()||b.id===sessao.barbeiro_id).map(b=>UI.choice({id:b.id,title:b.nome,detail:'Profissional',symbol:'user',selected:b.id===draft.barbeiro})).join('')}</div>`:step===3?`<label>Data do atendimento<input type="date" id="new-date" min="${today()}" max="${bookingMaxDate()}" value="${draft.data}" required></label><p class="muted">A disponibilidade considera duração do serviço, reservas e bloqueios.</p>`:step===4?'<div id="new-hours" class="hour-options">'+UI.loading('Consultando horários disponíveis…')+'</div>':`<div class="detail-facts">${[['Cliente',draft.nome],['WhatsApp',draft.telefone],['Serviço',service?.nome],['Profissional',barber?.nome],['Data e horário',dateLabel(draft.data)+' · '+draft.horario],['Valor',money(service?.preco||0)]].map(([label,value])=>`<div><small>${label}</small><strong>${esc(value)}</strong></div>`).join('')}</div>`;
  const dialog=AppShell.open('Novo agendamento',`<div class="booking-wizard-progress" aria-label="Etapa ${step+1} de 6">${Array.from({length:6},(_,i)=>`<span class="${i<=step?'done':''}"></span>`).join('')}</div><p class="step-heading">Etapa ${step+1} de 6</p><h3>${titles[step]}</h3><form id="internal-booking-form">${content}<div class="modal-actions"><button type="button" class="secondary" id="new-back">${step?'Voltar':'Cancelar'}</button><button id="new-next" type="submit" ${step===1&&!service||step===2&&!barber||step===4?'disabled':''}>${step===5?'Confirmar agendamento':'Continuar'}</button></div></form>`);
  dialog.oncancel=e=>{if(busy)e.preventDefault();};byId('new-back').onclick=()=>{if(busy)return;version++;if(step){step--;render();}else AppShell.close();};
  dialog.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{draft[step===1?'servico':'barbeiro']=b.dataset.choice;draft.horario='';render();});
  if(step===4){const request=++version;api('/api/publico/'+encodeURIComponent(sessao.slug)+'/disponibilidade?'+new URLSearchParams({barbeiro_id:draft.barbeiro,servico_id:draft.servico,data:draft.data})).then(data=>{if(request!==version||step!==4||!dialog.open)return;available=data.horarios;byId('new-hours').innerHTML=available.length?available.map(hour=>`<button type="button" class="hour-choice ${hour===draft.horario?'selected':''}" data-new-hour="${hour}">${hour}</button>`).join(''):UI.empty('Sem horários disponíveis','Volte e escolha outra data ou outro profissional.');byId('new-next').disabled=!available.includes(draft.horario);dialog.querySelectorAll('[data-new-hour]').forEach(b=>b.onclick=()=>{draft.horario=b.dataset.newHour;dialog.querySelectorAll('[data-new-hour]').forEach(x=>x.classList.toggle('selected',x===b));byId('new-next').disabled=false;});}).catch(err=>{if(request===version&&dialog.open){byId('new-hours').innerHTML=UI.empty('Não foi possível consultar',err.message);}});}
  byId('internal-booking-form').onsubmit=async e=>{e.preventDefault();if(busy)return;if(step===0){draft.nome=byId('new-client-name').value.trim();draft.telefone=byId('new-client-phone').value.trim();const phone=draft.telefone.replace(/\D/g,'');if(draft.nome.length<2||!([10,11].includes(phone.length)||phone.startsWith('55')&&[12,13].includes(phone.length))){mensagem('Informe nome e WhatsApp com DDD.',true);return;}}if(step===3){draft.data=byId('new-date').value;draft.horario='';}if(step<5){step++;render();return;}
   busy=true;dialog.querySelectorAll('button').forEach(b=>b.disabled=true);byId('new-next').textContent='Confirmando…';
   try{await api('/api/publico/'+encodeURIComponent(sessao.slug)+'/agendamentos',{method:'POST',body:JSON.stringify({cliente_nome:draft.nome,cliente_telefone:draft.telefone,servico_id:draft.servico,barbeiro_id:draft.barbeiro,data:draft.data,horario:draft.horario})});AppShell.close();mensagem('Agendamento criado.');try{reservas=await api('/api/agendamentos');byId('filtro-data').value=draft.data;agendaModo='dia';await mostrarAba('agenda');mensagem('Agendamento criado.');}catch{mensagem('Agendamento criado. Atualize a agenda para consultar.',true);}}
   catch(err){if(err.status===409){draft.horario='';step=4;render();}else{byId('new-next').textContent='Confirmar agendamento';dialog.querySelectorAll('button').forEach(b=>b.disabled=false);}mensagem(err.message+(err.status?'':' Confira a agenda antes de tentar novamente.'),true);}finally{busy=false;}
  };
 }render();
}
