const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const script=html.split('<script>')[1].split('</script>')[0];
new vm.Script(script);new vm.Script(fs.readFileSync(path.join(root,'pwa.js'),'utf8'));new vm.Script(fs.readFileSync(path.join(root,'design-system.js'),'utf8'));
new vm.Script(fs.readFileSync(path.join(root,'image-upload.js'),'utf8'));
const route=script.slice(script.indexOf('function bookingDeepLink()'),script.indexOf('async function iniciar()'));
const guide=script.slice(script.indexOf('function etapasConfiguracao('),script.indexOf('function renderPrimeirosPassos('));
(async()=>{
  await require('./test_agenda_live.cjs')();
  await require('./test_panel_ux.cjs')();
  const mapScript=script.slice(script.indexOf('function shopMapUrl('),script.indexOf('function shopLanding('));
  const mapCtx={URL,encodeURIComponent,config:{endereco:'Rua Teste, 10 & Centro'},esc:s=>String(s),UI:{icon:()=>''}};
  vm.createContext(mapCtx);vm.runInContext(mapScript,mapCtx);
  assert.equal(mapCtx.shopMapUrl(),'https://www.google.com/maps/search/?api=1&query=Rua%20Teste%2C%2010%20%26%20Centro');
  mapCtx.config.localizacao_url='https://maps.app.goo.gl/teste';assert.equal(mapCtx.shopMapUrl(),mapCtx.config.localizacao_url);
  assert.match(mapCtx.shopDirections('button'),/Como chegar/);
  mapCtx.config.localizacao_url='javascript:alert(1)';assert.match(mapCtx.shopMapUrl(),/google.com\/maps/);
  mapCtx.config={};assert.equal(mapCtx.shopDirections(),'');
  let drawn,closed=0;
  const imageCtx={Map,createImageBitmap:async()=>({width:4000,height:2000,close:()=>closed++}),document:{createElement:()=>{const canvas={getContext:()=>({drawImage:()=>drawn=[canvas.width,canvas.height]}),toBlob:cb=>cb({type:'image/webp',size:1024})};return canvas;}}};
  vm.createContext(imageCtx);vm.runInContext(fs.readFileSync(path.join(root,'image-upload.js'),'utf8')+';this.images=ShopImages;',imageCtx);
  await imageCtx.images.compress({type:'image/jpeg',size:5000000},'logo');assert.deepEqual(drawn,[512,256]);
  await imageCtx.images.compress({type:'image/png',size:5000000},'capa');assert.deepEqual(drawn,[1200,600]);assert.equal(closed,2);
  await assert.rejects(imageCtx.images.compress({type:'image/svg+xml',size:100},'logo'));
  await assert.rejects(imageCtx.images.compress({type:'image/jpeg',size:16000000},'logo'));
  const available=script.slice(script.indexOf('async function loadBookingAvailability('),script.indexOf('async function horarios()'));
  let active=0,peak=0;
  const slotsCtx={Map,URLSearchParams,config:{barbeiros:[{id:'a'},{id:'b'},{id:'c'},{id:'d'}]},slug:'loja',api:async url=>{active++;peak=Math.max(active,peak);await Promise.resolve();active--;const id=new URL(url,'https://example.com').searchParams.get('barbeiro_id');return {horarios:id==='a'?['10:00','09:00']:id==='b'?['09:30','09:00']:[]};}};
  vm.createContext(slotsCtx);vm.runInContext(fs.readFileSync(path.join(root,'promocoes.js'),'utf8'),slotsCtx);vm.runInContext(available,slotsCtx);
  const choice={preferencia:'*',data:'2026-10-05',servico:{id:'corte'}};
  const slots=await slotsCtx.loadBookingAvailability(choice);
  assert.deepEqual([...slots.keys()],['09:00','09:30','10:00']);assert.deepEqual([...slots.get('09:00')],['a','b']);assert.ok(peak<=3);
  const only=await slotsCtx.loadBookingAvailability({...choice,preferencia:'b',barbeiro:{id:'b'}});assert.deepEqual([...only.keys()],['09:00','09:30']);
  slotsCtx.api=async()=>{throw Error('conex�o indispon�vel');};await assert.rejects(slotsCtx.loadBookingAvailability(choice));
  const uiCtx={esc:s=>String(s),document:{body:{style:{setProperty(){}}}}};vm.createContext(uiCtx);vm.runInContext(fs.readFileSync(path.join(root,'design-system.js'),'utf8')+';this.ui=UI;',uiCtx);
  const calendar=uiCtx.ui.calendar({month:'2026-10',selected:'2026-10-05',min:'2026-10-03',max:'2027-04-01',days:[0,1,2,3,4]});
  assert.match(calendar,/data-date="2026-10-03"[^>]*disabled/);assert.match(calendar,/data-date="2026-10-05"[^>]*aria-pressed="true"/);assert.match(calendar,/aria-label="Mês anterior" disabled/);
  for(const status of [200,401,500]){
    let panel=false,form=false;
    const ctx={URLSearchParams,api:async()=>{if(status!==200)throw {status};},location:{search:'',replace:p=>{panel=p==='/painel';}},acesso:()=>{form=true;}};
    vm.createContext(ctx);vm.runInContext(route,ctx);
    if(status===500)await assert.rejects(ctx.entrada());else await ctx.entrada();
    assert.equal(panel,status===200);assert.equal(form,status===401);
    ctx.location.search='?agendamento=42&notificacao='+'a'.repeat(64);assert.equal(ctx.bookingDeepLink(),'?agendamento=42&notificacao='+'a'.repeat(64)+'#agenda');
    ctx.location.search='?agendamento=https://evil.test';assert.equal(ctx.bookingDeepLink(),'');
  }
  const guideCtx={};vm.createContext(guideCtx);vm.runInContext(guide,guideCtx);
  const config={nome:'Loja',whatsapp:'',barbeiros:[],servicos:[],dias:[],periodos:[]};
  assert.equal(guideCtx.etapasConfiguracao(config,{ativa:false}).filter(s=>s.pronto).length,0);
  Object.assign(config,{whatsapp:'11999990000',barbeiros:[{}],servicos:[{}],dias:[0],periodos:[{}]});
  assert.equal(guideCtx.etapasConfiguracao(config,{ativa:false}).filter(s=>s.pronto).length,4);
  assert.equal(guideCtx.etapasConfiguracao(config,{ativa:true}).filter(s=>s.pronto).length,5);
  const events={},offline={page:'offline'},online={page:'online'},cacheReads=[];
  let networkFails=false;
  const ctx={self:{addEventListener:(name,fn)=>events[name]=fn},fetch:async()=>{if(networkFails)throw Error('offline');return online;},caches:{match:async name=>{cacheReads.push(name);return offline;}}};
  vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(root,'sw.js'),'utf8'),ctx);
  let response;
  events.fetch({request:{method:'GET',mode:'navigate'},respondWith:p=>response=p});
  assert.equal(await response,online);assert.equal(cacheReads.length,0);
  networkFails=true;events.fetch({request:{method:'GET',mode:'navigate'},respondWith:p=>response=p});
  assert.equal(await response,offline);assert.equal(cacheReads[0],'/offline.html');
  for(const request of [{method:'POST',mode:'navigate'},{method:'GET',mode:'cors'}]){
    let intercepted=false;events.fetch({request,respondWith:()=>intercepted=true});assert.equal(intercepted,false);
  }
  const controls={'instalar-app':{},'ajuda-app':{hidden:true},'instalacao-app':{hidden:false},'conexao-app':{hidden:true}};
  const uiEvents={};const ui={document:{getElementById:id=>controls[id]},matchMedia:()=>({matches:false}),navigator:{onLine:true},window:{addEventListener:(name,fn)=>uiEvents[name]=fn}};
  vm.createContext(ui);vm.runInContext(fs.readFileSync(path.join(root,'pwa.js'),'utf8'),ui);
  await controls['instalar-app'].onclick();assert.equal(controls['ajuda-app'].hidden,false);
  ui.navigator.onLine=false;uiEvents.offline();assert.equal(controls['conexao-app'].hidden,false);
  ui.navigator.onLine=true;uiEvents.online();assert.equal(controls['conexao-app'].hidden,true);
  let prompted=false;uiEvents.beforeinstallprompt({preventDefault(){},prompt:async()=>prompted=true,userChoice:Promise.resolve({outcome:'dismissed'})});
  await controls['instalar-app'].onclick();assert.equal(prompted,true);assert.equal(controls['instalacao-app'].hidden,false);
  uiEvents.appinstalled();assert.equal(controls['instalacao-app'].hidden,true);
  console.log('OK: login, progresso, instala��o, conex�o e nenhuma altera��o/API armazenada offline.');
})().catch(err=>{console.error(err);process.exitCode=1;});

require('./test_produtos_frontend.cjs');
